/**
 * Database Triggers Integration Tests
 *
 * Tests auto-generated order numbers and KDS ticket creation triggers.
 */

import {
  createServiceClient,
  cleanupRows,
  waitFor,
  SEED,
} from "./helpers";
import { randomUUID } from "crypto";

describe("Database Triggers", () => {
  const createdOrderIds: number[] = [];
  const createdOrderItemIds: number[] = [];
  const createdKDSTicketIds: number[] = [];

  afterAll(async () => {
    await cleanupRows("kds_tickets", createdKDSTicketIds);
    await cleanupRows("order_items", createdOrderItemIds);
    await cleanupRows("orders", createdOrderIds);
  });

  it("order_number is auto-generated by trigger on insert", async () => {
    const service = createServiceClient();

    const { data: waiterProfile } = await service
      .from("profiles")
      .select("id")
      .eq("role", "waiter")
      .eq("tenant_id", SEED.tenantId)
      .limit(1)
      .single();

    const { data: terminal } = await service
      .from("pos_terminals")
      .select("id")
      .eq("branch_id", SEED.branchQ1)
      .eq("is_active", true)
      .limit(1)
      .single();

    // Insert with a placeholder order_number (required by NOT NULL)
    // The generate_order_number function is called explicitly, not via trigger
    // So we test by using the function directly
    const { data: orderNum, error: fnErr } = await service.rpc(
      "generate_order_number",
      { p_branch_id: SEED.branchQ1 },
    );

    expect(fnErr).toBeNull();
    expect(orderNum).not.toBeNull();
    // Format: {code}-{YYYYMMDD}-{seq}
    expect(orderNum).toMatch(/^Q1-\d{8}-\d{3}$/);

    // Use the generated number for an actual order
    const { data: order, error: orderErr } = await service
      .from("orders")
      .insert({
        order_number: orderNum as string,
        branch_id: SEED.branchQ1,
        terminal_id: terminal!.id,
        type: "dine_in",
        status: "draft",
        subtotal: 50000,
        total: 50000,
        created_by: waiterProfile!.id,
        idempotency_key: randomUUID(),
      })
      .select("id, order_number")
      .single();

    expect(orderErr).toBeNull();
    expect(order!.order_number).toBe(orderNum);
    createdOrderIds.push(order!.id);
  });

  it("KDS tickets are created when order transitions to confirmed", async () => {
    const service = createServiceClient();

    // Check if KDS stations exist with category mappings
    const { data: stations } = await service
      .from("kds_stations")
      .select("id, branch_id")
      .eq("branch_id", SEED.branchQ1)
      .eq("is_active", true);

    if (!stations || stations.length === 0) {
      // No KDS stations configured — skip
      return;
    }

    const { data: stationCategories } = await service
      .from("kds_station_categories")
      .select("station_id, category_id")
      .in(
        "station_id",
        stations.map((s) => s.id),
      );

    if (!stationCategories || stationCategories.length === 0) {
      // No category mappings — trigger won't fire
      return;
    }

    // Find a menu_item that belongs to a mapped category
    const categoryIds = stationCategories.map((sc) => sc.category_id);
    const { data: menuItems } = await service
      .from("menu_items")
      .select("id, category_id")
      .in("category_id", categoryIds)
      .limit(1);

    if (!menuItems || menuItems.length === 0) return;

    const orderId = createdOrderIds[0]!;

    // Add an order item with a mapped category
    const { data: item } = await service
      .from("order_items")
      .insert({
        order_id: orderId,
        menu_item_id: menuItems[0]!.id,
        quantity: 1,
        unit_price: 50000,
        item_total: 50000,
        status: "pending",
      })
      .select("id")
      .single();

    if (item) createdOrderItemIds.push(item.id);

    // Transition order: draft → confirmed (triggers create_kds_tickets)
    await service
      .from("orders")
      .update({ status: "confirmed" })
      .eq("id", orderId);

    // Wait for KDS tickets to be created (trigger is synchronous via AFTER UPDATE)
    await waitFor(
      async () => {
        const { data: tickets } = await service
          .from("kds_tickets")
          .select("id")
          .eq("order_id", orderId);
        return tickets !== null && tickets.length > 0;
      },
      { timeout: 5000, label: "KDS tickets created" },
    );

    const { data: tickets } = await service
      .from("kds_tickets")
      .select("id, order_id, station_id, status, items")
      .eq("order_id", orderId);

    expect(tickets).not.toBeNull();
    expect(tickets!.length).toBeGreaterThan(0);
    expect(tickets![0]!.status).toBe("pending");
    expect(tickets![0]!.items).not.toBeNull();

    for (const t of tickets!) {
      createdKDSTicketIds.push(t.id);
    }
  });
});
